spring:
  application:
    name: gateway
  cloud:
#    gateway:
#      routes:
#        - id: movies-info-service
#          uri: lb://MOVIES-INFO-SERVICE
#          predicates:
#            - Path=/movieinfos/**
#          filters:
#            - "RewritePath=/movieinfos(?<segment>/?.*),/v1/movieinfos${segment}"
#        - id: movies-review-service
#          uri: lb://MOVIES-REVIEW-SERVICE
#          predicates:
#            - Path=/reviews
#          filters:
#            - "RewritePath=/reviews(?<segment>/?.*),/v1/reviews${segment}"
#        - id: movies-service
#          uri: lb://MOVIES-SERVICE
#          predicates:
#            - Path=/movies/**, /v2/movies/**
#          filters:
#            - "RewritePath=/movies(?<segment>/?.*),/v1/movies${segment}"
#        - id: service-registry
#          uri: http://localhost:8761
#          predicates:
#            - Path=/eureka/main
#          filters:
#            - SetPath=/
#        - id: service-registry-static
#          uri: http://localhost:8761
#          predicates:
#            - Path=/eureka/**
server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
  health:
    circuitbreakers:
      enabled: true
  metrics:
    enable:
      resilience4j.circuitbreaker: true

#Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      gatewayService:
        registerHealthIndicator: true           # Enables actuator health info
        slidingWindowType: COUNT_BASED          # COUNT_BASED or TIME_BASED
        slidingWindowSize: 10                   # Number of calls to keep in window
        minimumNumberOfCalls: 5                 # Minimum calls before calculating failure rate
        failureRateThreshold: 50                # % of failures to trip circuit
        waitDurationInOpenState: 10s            # How long to stay OPEN before attempting HALF_OPEN
        permittedNumberOfCallsInHalfOpenState: 3 # How many test calls allowed in HALF_OPEN
        automaticTransitionFromOpenToHalfOpenEnabled: true # Automatically move from OPEN to HALF_OPEN after waitDuration
        recordExceptions:
          - java.net.ConnectException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.reactive.function.client.WebClientRequestException